on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build
        run: yarn && yarn build

      - name: Upload
        run: node qiniu.js ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }}

      - name: Publish
        run: |
          echo it works!
