name: deploy

on:
  push:
    branches:
      - master

jobs:
  merge:
    name: merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge to deploy branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'deploy'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    needs: merge
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: deploy

      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build
        run: yarn && yarn build

      - name: Commit
        run: |
          git config --local user.email "icesilt@outlook.com"
          git config --local user.name "falstack"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Add changes"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'deploy'
          force: true

  upload:
    needs: [merge, build]
    name: upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: deploy

      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Upload
        run: |
          yarn
          node qiniu.js ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }}

  publish:
    needs: [merge, build, upload]
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          name: id_rsa
          private-key: ${{ secrets.PRIVATE_KEY_PEM }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: |
            Host prod
              HostName ${{ secrets.SERVER_IP }}
              Port ${{ secrets.SERVER_PORT }}
              User ${{ secrets.SERVER_USER }}
              IdentityFile ~/.ssh/id_rsa

      - name: Publish
        run: |
          ssh prod -tt
          cd ${{ secrets.SERVER_PATH }}
          git pull
          yarn
          pm2 startOrReload pm2.config.js --env=production -i max

